export const CREATE_RECIPE = 'CREATE_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const RATE_RECIPE = 'RATE_RECIPE';

export const LOAD_RECIPES_SUCCESS = "LOAD_RECIPES_SUCCESS";

export const LOAD_RECIPE_REQUEST = "LOAD_RECIPE_REQUEST";
export const LOAD_RECIPE_SUCCESS = "LOAD_RECIPE_SUCCESS";
export const LOAD_RECIPE_ERROR = "LOAD_RECIPE_ERROR";

export const CREATE_RECIPE_REQUEST = "CREATE_RECIPE_REQUEST";
export const CREATE_RECIPE_SUCCESS = "CREATE_RECIPE_SUCCESS";
export const CREATE_RECIPE_ERROR = "CREATE_RECIPE_ERROR";

export const UPDATE_RECIPE_SUCCESS = "UPDATE_RECIPE_SUCCESS";
export const UPDATE_RECIPE_ERROR = "UPDATE_RECIPE_ERROR";

export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const SET_NAME_FILTER = 'SET_NAME_FILTER';
export const SET_CURRENT_RECIPEID = 'SET_CURRENT_RECIPEID';


export const CategoryFilters = {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_PASTAS: 'SHOW_PASTAS',
    SHOW_SALADS: 'SHOW_SALADS',
    SHOW_MEAT: 'SHOW_MEAT',
    SHOW_DESSERTS: 'SHOW_DESSERTS'
};